# Generated by Django 3.2.15 on 2022-10-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_conatact_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
